/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
import petstoreSidebar from './docs/api/staking-api/sidebar';
import babylongRpcSidebar from './docs/api/babylon-gRPC/sidebar';

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  guides: [{ type: 'autogenerated', dirName: 'guides' }],
  operators: [{ type: 'autogenerated', dirName: 'operators' }],
  developers: [{ type: 'autogenerated', dirName: 'developers' }],
  stakingApi: [
    {
      type: 'category',
      label: 'Babylon Staking API',
      link: {
        type: 'doc',
        id: 'api/staking-api/babylon-staking-api',
      },
      items: petstoreSidebar,
    },
  ],
  babylonRpc: [
    {
      type: 'category',
      label: 'Babylon gRPC',
      link: {
        type: 'doc',
        id: 'api/babylon-gRPC/babylon-grpc-api-docs',
      },
      items: babylongRpcSidebar,
    },
  ],
};

module.exports = sidebars;
