/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
// @ts-check

const stakingApiSidebar = require('./docs/api/staking-api/sidebar').default;
const babylongRpcSidebar = require('./docs/api/babylon-gRPC/sidebar').default;
const cometBFTSidebar = require('./docs/api/comet-bft/sidebar').default;

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // Overview sidebar: includes guides, plus stakers/developers/operators content
  guides: [
    {
      type: 'category',
      label: 'Overview',
      collapsible: false,
      collapsed: false,
      className: 'overview_sidebar_header',
      link: {
        type: 'doc',
        id: 'guides/overview/overview',
      },
      items: [
        { type: 'link', label: 'Trustless Bitcoin Vault', href: '/trustless-bitcoin-vault/' },
        {
          type: 'category',
          label: 'Bitcoin Staking',
          collapsible: true,
          collapsed: true,
          link: {
            type: 'doc',
            id: 'guides/overview/bitcoin_staking',
          },
          items: [
            { type: 'autogenerated', dirName: 'stakers' },
            { type: 'autogenerated', dirName: 'developers/bitcoin_staking' },
          ],
        },
        {
          type: 'category',
          label: 'Babylon Genesis',
          collapsible: true,
          collapsed: true,
          link: {
            type: 'doc',
            id: 'guides/overview/babylon_genesis/babylon_genesis',
          },
          items: [
            // Chain Overview
            { type: 'autogenerated', dirName: 'guides/overview/babylon_genesis/architecture' },
            { type: 'doc', id: 'guides/overview/babylon_genesis/baby_tokenomics' },
            { type: 'autogenerated', dirName: 'guides/overview/babylon_genesis/governance' },
            // Group 2: Build on Genesis
            {
              type: 'category',
              label: 'Build on Genesis',
              collapsible: true,
              collapsed: true,
              items: [
                { type: 'autogenerated', dirName: 'developers/babylon_genesis_chain' },
              ],
            },
            // Group 3: Run a Node
            {
              type: 'category',
              label: 'Run a Node',
              collapsible: true,
              collapsed: true,
              items: [
                { type: 'autogenerated', dirName: 'operators' },
              ],
            },
            // Group 4: Specifications
            { type: 'autogenerated', dirName: 'guides/overview/babylon_genesis/specifications' },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Research',
      collapsible: true,
      collapsed: true,
      className: 'research_sidebar_header',
      items: [
        { type: 'autogenerated', dirName: 'guides/research' },
      ],
    },
    {
      type: 'category',
      label: 'Security',
      collapsible: true,
      collapsed: true,
      className: 'security_sidebar_header',
      items: [
        { type: 'autogenerated', dirName: 'guides/security' },
      ],
    },
    {
      type: 'category',
      label: 'Support',
      collapsible: true,
      collapsed: true,
      className: 'support_sidebar_header',
      items: [
        { type: 'autogenerated', dirName: 'guides/support' },
      ],
    },
  ],
  // Trustless Bitcoin Vault sidebar — top-nav home for the open Testnet docs
  trustlessBitcoinVault: [{ type: 'autogenerated', dirName: 'trustless-bitcoin-vault' }],
  stakingApi: [
    {
      type: 'category',
      label: 'Babylon Staking API',
      link: {
        type: 'doc',
        id: 'api/staking-api/babylon-staking-api',
      },
      items: stakingApiSidebar,
    },
  ],
  babylonRpc: [
    {
      type: 'category',
      label: 'Babylon gRPC',
      link: {
        type: 'doc',
        id: 'api/babylon-gRPC/babylon-grpc-api-docs',
      },
      items: babylongRpcSidebar,
    },
  ],
  cometBFT:[
    {
      type: 'category',
      label: 'CometBFT',
      link: {
        type: 'doc',
        id: 'api/comet-bft/babylon-grpc-api-docs',
      },
      items: cometBFTSidebar,
    },
  ],
};

module.exports = sidebars;
