/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
// @ts-check

const stakingApiSidebar = require('./docs/api/staking-api/sidebar').default;
const babylongRpcSidebar = require('./docs/api/babylon-gRPC/sidebar').default;
const cometBFTSidebar = require('./docs/api/comet-bft/sidebar').default;

const showHiddenTrustlessBitcoinVaultSections = false;

const hiddenTrustlessBitcoinVaultSections = showHiddenTrustlessBitcoinVaultSections
  ? [
      {
        type: 'category',
        label: 'Research',
        className: 'research_sidebar_header',
        items: [{ type: 'autogenerated', dirName: 'trustless-bitcoin-vault/research' }],
      },
      {
        type: 'category',
        label: 'Security',
        className: 'security_sidebar_header',
        items: [{ type: 'autogenerated', dirName: 'trustless-bitcoin-vault/security' }],
      },
    ]
  : [];

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // Overview sidebar: includes guides, plus stakers/developers/operators content
  guides: [
    {
      type: 'category',
      label: 'Overview',
      collapsible: false,
      collapsed: false,
      className: 'overview_sidebar_header',
      link: {
        type: 'doc',
        id: 'guides/overview/overview',
      },
      items: [
        { type: 'link', label: 'Trustless Bitcoin Vault', href: '/trustless-bitcoin-vault/' },
        {
          type: 'category',
          label: 'Bitcoin Staking',
          collapsible: true,
          collapsed: true,
          link: {
            type: 'doc',
            id: 'guides/overview/bitcoin_staking/index',
          },
          items: [
            { type: 'autogenerated', dirName: 'stakers' },
            { type: 'autogenerated', dirName: 'developers/bitcoin_staking' },
            {
              type: 'category',
              label: 'Research',
              className: 'research_sidebar_header',
              link: {
                type: 'doc',
                id: 'guides/overview/bitcoin_staking/research/index',
              },
              items: [
                'guides/overview/bitcoin_staking/research/btc_staking_litepaper',
                'guides/overview/bitcoin_staking/research/btc_timestamping',
                'guides/overview/bitcoin_staking/research/babe_verification',
                'guides/overview/bitcoin_staking/research/btc_trustless_vault',
              ],
            },
            {
              type: 'category',
              label: 'Security',
              className: 'security_sidebar_header',
              link: {
                type: 'doc',
                id: 'guides/overview/bitcoin_staking/security/index',
              },
              items: [
                'guides/overview/bitcoin_staking/security/audit_reports',
                'guides/overview/bitcoin_staking/security/bug_bounties',
              ],
            },
          ],
        },
        {
          type: 'category',
          label: 'Babylon Genesis',
          collapsible: true,
          collapsed: true,
          link: {
            type: 'doc',
            id: 'guides/overview/babylon_genesis/babylon_genesis',
          },
          items: [
            // Chain Overview
            { type: 'autogenerated', dirName: 'guides/overview/babylon_genesis/architecture' },
            { type: 'doc', id: 'guides/overview/babylon_genesis/baby_tokenomics' },
            { type: 'autogenerated', dirName: 'guides/overview/babylon_genesis/governance' },
            // Group 2: Build on Genesis
            {
              type: 'category',
              label: 'Build on Genesis',
              collapsible: true,
              collapsed: true,
              items: [
                { type: 'autogenerated', dirName: 'developers/babylon_genesis_chain' },
              ],
            },
            // Group 3: Run a Node
            {
              type: 'category',
              label: 'Run a Node',
              collapsible: true,
              collapsed: true,
              items: [
                { type: 'autogenerated', dirName: 'operators' },
              ],
            },
            // Group 4: Specifications
            { type: 'autogenerated', dirName: 'guides/overview/babylon_genesis/specifications' },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Support',
      collapsible: true,
      collapsed: true,
      className: 'support_sidebar_header',
      items: [
        { type: 'autogenerated', dirName: 'guides/support' },
      ],
    },
  ],
  // Trustless Bitcoin Vault sidebar — top-nav home for the open Testnet docs
  trustlessBitcoinVault: [
    {
      type: 'category',
      label: 'Trustless Bitcoin Vault',
      collapsible: false,
      collapsed: false,
      className: 'overview_sidebar_header',
      link: {
        type: 'doc',
        id: 'trustless-bitcoin-vault/index',
      },
      items: [
        {
          type: 'category',
          label: 'Start Here',
          className: 'overview_sidebar_header',
          link: { type: 'generated-index', slug: '/trustless-bitcoin-vault/start-here' },
          items: [{ type: 'autogenerated', dirName: 'trustless-bitcoin-vault/start-here' }],
        },
        {
          type: 'category',
          label: 'Testnet Info',
          className: 'specs_sidebar_header',
          link: { type: 'generated-index', slug: '/trustless-bitcoin-vault/testnet-info' },
          items: [{ type: 'autogenerated', dirName: 'trustless-bitcoin-vault/testnet-info' }],
        },
        {
          type: 'category',
          label: 'Use TBV Testnet for Lending',
          className: 'btc_stakers_sidebar_header',
          link: { type: 'generated-index', slug: '/trustless-bitcoin-vault/use-for-lending' },
          items: [{ type: 'autogenerated', dirName: 'trustless-bitcoin-vault/use-for-lending' }],
        },
        {
          type: 'category',
          label: 'Technical Details',
          className: 'architecture_sidebar_header',
          link: { type: 'generated-index', slug: '/trustless-bitcoin-vault/technical-details' },
          items: [{ type: 'autogenerated', dirName: 'trustless-bitcoin-vault/technical-details' }],
        },
        {
          type: 'category',
          label: 'Reference',
          className: 'support_sidebar_header',
          link: { type: 'generated-index', slug: '/trustless-bitcoin-vault/reference' },
          items: [{ type: 'autogenerated', dirName: 'trustless-bitcoin-vault/reference' }],
        },
        ...hiddenTrustlessBitcoinVaultSections,
      ],
    },
  ],
  stakingApi: [
    {
      type: 'category',
      label: 'Babylon Staking API',
      link: {
        type: 'doc',
        id: 'api/staking-api/babylon-staking-api',
      },
      items: stakingApiSidebar,
    },
  ],
  babylonRpc: [
    {
      type: 'category',
      label: 'Babylon gRPC',
      link: {
        type: 'doc',
        id: 'api/babylon-gRPC/babylon-grpc-api-docs',
      },
      items: babylongRpcSidebar,
    },
  ],
  cometBFT:[
    {
      type: 'category',
      label: 'CometBFT',
      link: {
        type: 'doc',
        id: 'api/comet-bft/babylon-grpc-api-docs',
      },
      items: cometBFTSidebar,
    },
  ],
};

module.exports = sidebars;
