import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebar: SidebarsConfig = {
  apisidebar: [
    {
      type: "doc",
      id: "api/babylon-gRPC/babylon-grpc-api-docs",
    },
    {
      type: "category",
      label: "btccheckpoint",
      link: {
        type: "doc",
        id: "api/babylon-gRPC/btccheckpoint",
      },
      items: [
        {
          type: "doc",
          id: "api/babylon-gRPC/btc-checkpoints-info",
          label: "BtcCheckpointsInfo",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/btc-checkpoint-params",
          label: "BtcCheckpointParams",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/btc-checkpoint-info",
          label: "BtcCheckpointInfo",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/epoch-submissions",
          label: "EpochSubmissions",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "btclightclient",
      link: {
        type: "doc",
        id: "api/babylon-gRPC/btclightclient",
      },
      items: [
        {
          type: "doc",
          id: "api/babylon-gRPC/base-header",
          label: "BaseHeader",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/contains",
          label: "Contains",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/contains-bytes",
          label: "ContainsBytes",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/header-depth",
          label: "HeaderDepth",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/hashes",
          label: "Hashes",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/main-chain",
          label: "MainChain",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/btc-light-client-params",
          label: "BtcLightClientParams",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/tip",
          label: "Tip",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "btcstaking",
      link: {
        type: "doc",
        id: "api/babylon-gRPC/btcstaking",
      },
      items: [
        {
          type: "doc",
          id: "api/babylon-gRPC/btc-delegation",
          label: "BTCDelegation",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/btc-delegations",
          label: "BTCDelegations",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/finality-providers",
          label: "FinalityProviders",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/finality-provider-delegations",
          label: "FinalityProviderDelegations",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/finality-provider",
          label: "FinalityProvider",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/largest-btc-re-org",
          label: "LargestBtcReOrg",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/params",
          label: "Params",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/params-by-btc-height",
          label: "ParamsByBTCHeight",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/params-by-version",
          label: "ParamsByVersion",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/params-versions",
          label: "ParamsVersions",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "btcstkconsumer",
      link: {
        type: "doc",
        id: "api/babylon-gRPC/btcstkconsumer",
      },
      items: [
        {
          type: "doc",
          id: "api/babylon-gRPC/consumer-registry-list",
          label: "ConsumerRegistryList",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/consumers-registry",
          label: "ConsumersRegistry",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/finality-provider-consumer",
          label: "FinalityProviderConsumer",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/finality-provider-consumer",
          label: "FinalityProviderConsumer",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/finality-providers-consumer",
          label: "FinalityProvidersConsumer",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/btc-stk-consumer-params",
          label: "BtcStkConsumerParams",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "checkpointing",
      link: {
        type: "doc",
        id: "api/babylon-gRPC/checkpointing",
      },
      items: [
        {
          type: "doc",
          id: "api/babylon-gRPC/bls-public-key-list",
          label: "BlsPublicKeyList",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/epoch-status",
          label: "EpochStatus",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/recent-epoch-status-count",
          label: "RecentEpochStatusCount",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/last-checkpoint-with-status",
          label: "LastCheckpointWithStatus",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/raw-checkpoint",
          label: "RawCheckpoint",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/raw-checkpoints",
          label: "RawCheckpoints",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/raw-checkpoint-list",
          label: "RawCheckpointList",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "epoching",
      link: {
        type: "doc",
        id: "api/babylon-gRPC/epoching",
      },
      items: [
        {
          type: "doc",
          id: "api/babylon-gRPC/current-epoch",
          label: "CurrentEpoch",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/delegation-lifecycle",
          label: "DelegationLifecycle",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/epochs-info",
          label: "EpochsInfo",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/epoch-info",
          label: "EpochInfo",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/epoch-msgs",
          label: "EpochMsgs",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/epoch-val-set",
          label: "EpochValSet queries the validator set of a given epoch",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/latest-epoch-msgs",
          label: "LatestEpochMsgs",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/epoching-params",
          label: "EpochingParams",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/validator-lifecycle",
          label: "ValidatorLifecycle",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "incentive",
      link: {
        type: "doc",
        id: "api/babylon-gRPC/incentive",
      },
      items: [
        {
          type: "doc",
          id: "api/babylon-gRPC/reward-gauges",
          label: "RewardGauge",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/btc-staking-gauge",
          label: "BTCStakingGauge",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/delegator-withdraw-address",
          label: "DelegatorWithdrawAddress",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/delegation-rewards",
          label: "DelegationRewards",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/incentive-params",
          label: "IncentiveParams",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "mint",
      link: {
        type: "doc",
        id: "api/babylon-gRPC/mint",
      },
      items: [
        {
          type: "doc",
          id: "api/babylon-gRPC/annual-provisions",
          label: "AnnualProvisions",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/genesis-time",
          label: "GenesisTime",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/inflation-rate",
          label: "InflationRate",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "finality",
      items: [
        {
          type: "doc",
          id: "api/babylon-gRPC/activated-height",
          label: "ActivatedHeight",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/list-blocks",
          label: "ListBlocks",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/block",
          label: "Block",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/list-evidences",
          label: "ListEvidences",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/evidence",
          label: "Evidence",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/finality-provider-current-power",
          label: "FinalityProviderCurrentPower",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/finality-provider-power-at-height",
          label: "FinalityProviderPowerAtHeight",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/list-pub-rand-commit",
          label: "ListPubRandCommit",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/list-public-randomness",
          label: "ListPublicRandomness",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/active-finality-providers-at-height",
          label: "ActiveFinalityProvidersAtHeight",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/finality-params",
          label: "FinalityParams",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/signing-infos",
          label: "SigningInfos",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/signing-info",
          label: "SigningInfo",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/votes-at-height",
          label: "VotesAtHeight",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "monitor",
      items: [
        {
          type: "doc",
          id: "api/babylon-gRPC/reported-checkpoint-btc-height",
          label: "ReportedCheckpointBtcHeight",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/ended-epoch-btc-height",
          label: "EndedEpochBtcHeight",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "zoneconcierge",
      items: [
        {
          type: "doc",
          id: "api/babylon-gRPC/header",
          label: "Header",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/chain-list",
          label: "ChainList",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/chains-info",
          label: "ChainsInfo",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/epoch-chains-info",
          label: "EpochChainsInfo",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/finalized-chain-info-until-height",
          label: "FinalizedChainInfoUntilHeight",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/finalized-chains-info",
          label: "FinalizedChainsInfo",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/list-headers",
          label: "ListHeaders",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/list-epoch-headers",
          label: "ListEpochHeaders",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/zone-concierge-params",
          label: "ZoneConciergeParams",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "CometBFT",
      items: [
        {
          type: "doc",
          id: "api/babylon-gRPC/broadcast-tx-sync",
          label: "Returns with the response from CheckTx. Does not wait for DeliverTx result.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/broadcast-tx-async",
          label: "Returns right away, with no response. Does not wait for CheckTx nor DeliverTx results.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/broadcast-tx-commit",
          label: "Returns with the responses from CheckTx and DeliverTx.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/check-tx",
          label: "Checks the transaction without executing it.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/health",
          label: "Node heartbeat",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/status",
          label: "Node Status",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/net-info",
          label: "Network information",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/dial-seeds",
          label: "Dial Seeds (Unsafe)",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/dial-peers",
          label: "Add Peers/Persistent Peers (unsafe)",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/blockchain",
          label: "Get block headers (max: 20) for minHeight <= height <= maxHeight.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/header",
          label: "Get header at a specified height",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/header-by-hash",
          label: "Get header by hash",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/block",
          label: "Get block at a specified height",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/block-by-hash",
          label: "Get block by hash",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/block-results",
          label: "Get block results at a specified height",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/commit",
          label: "Get commit results at a specified height",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/validators",
          label: "Get validator set at a specified height",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/genesis",
          label: "Get Genesis",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/genesis-chunked",
          label: "Get Genesis in multiple chunks",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/dump-consensus-state",
          label: "Get consensus state",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/consensus-state",
          label: "Get consensus state",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/consensus-params",
          label: "Get consensus parameters",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/unconfirmed-txs",
          label: "Get the list of unconfirmed transactions",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/num-unconfirmed-txs",
          label: "Get data about unconfirmed transactions",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/tx-search",
          label: "Search for transactions",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/block-search",
          label: "Search for blocks by FinalizeBlock events",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/tx",
          label: "Get transactions by hash",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/abci-info",
          label: "Get info about the application.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/abci-query",
          label: "Query the application for some information.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/broadcast-evidence",
          label: "Broadcast evidence of the misbehavior.",
          className: "api-method get",
        },
      ],
    },
  ],
};

export default sidebar.apisidebar;
