import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebar: SidebarsConfig = {
  apisidebar: [
    {
      type: "doc",
      id: "api/babylon-gRPC/babylon-grpc-api-docs",
    },
    {
      type: "category",
      label: "Babylon",
      items: [
        {
          type: "doc",
          id: "api/babylon-gRPC/btc-checkpoints-info",
          label: "BtcCheckpointsInfo returns checkpoint info for a range of epochs",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/btc-checkpoint-params",
          label: "Parameters queries the parameters of the module.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/btc-checkpoint-info",
          label: "BtcCheckpointInfo returns checkpoint info for a given epoch",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/epoch-submissions",
          label: "EpochSubmissions returns all submissions for a given epoch",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/base-header",
          label: "BaseHeader returns the base BTC header of the chain. This header is defined\non genesis.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/contains",
          label: "Contains checks whether a hash is maintained by the module.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/contains-bytes",
          label: "ContainsBytes is a temporary method that\nchecks whether a hash is maintained by the module.\nSee discussion at https://github.com/babylonlabs-io/babylon/pull/132\nfor more details.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/header-depth",
          label: "HeaderDepth returns the depth of the header in main chain or error if the\nblock is not found or it exists on fork",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/hashes",
          label: "Hashes retrieves the hashes maintained by the module.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/main-chain",
          label: "MainChain returns the canonical chain",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/btc-light-client-params",
          label: "Params queries the parameters of the module.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/tip",
          label: "Tip return best header on canonical chain",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/btc-delegation",
          label: "BTCDelegation retrieves delegation by corresponding staking tx hash",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/btc-delegations",
          label: "BTCDelegations queries all BTC delegations under a given status",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/finality-providers",
          label: "FinalityProviders queries all finality providers",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/finality-provider-delegations",
          label: "FinalityProviderDelegations queries all BTC delegations of the given\nfinality provider",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/finality-provider",
          label: "FinalityProvider info about one finality provider",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/largest-btc-re-org",
          label: "LargestBtcReOrg retrieves the largest BTC reorg",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/params",
          label: "Parameters queries the parameters of the module.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/params-by-btc-height",
          label: "ParamsByBTCHeight queries the parameters of the module for a specific BTC\nheight",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/params-by-version",
          label: "ParamsByVersion queries the parameters of the module for a specific version\nof past params.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/params-versions",
          label: "ParamsVersions queries all the parameters of the module with version.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/consumer-registry-list",
          label: "ConsumerRegistryList queries the list of consumers that are registered to Babylon",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/consumers-registry",
          label: "ConsumersRegistry queries the latest info for a given list of consumers in Babylon's view",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/finality-provider-consumer",
          label: "FinalityProvider info about one finality provider",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/finality-provider-consumer",
          label: "FinalityProviderConsumer info about one finality provider's consumer id",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/finality-providers-consumer",
          label: "FinalityProviders queries all finality providers for a given consumer",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/btc-stk-consumer-params",
          label: "Parameters queries the parameters of the module.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/bls-public-key-list",
          label: "BlsPublicKeyList queries a list of bls public keys of the validators at a\ngiven epoch number.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/epoch-status",
          label: "EpochStatus queries the status of the checkpoint at a given epoch",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/recent-epoch-status-count",
          label: "RecentEpochStatusCount queries the number of epochs with each status in\nrecent epochs",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/last-checkpoint-with-status",
          label: "LastCheckpointWithStatus queries the last checkpoint with a given status or\na more matured status",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/raw-checkpoint",
          label: "RawCheckpoint queries a checkpoints at a given epoch number.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/raw-checkpoints",
          label: "RawCheckpoints queries checkpoints for a epoch range specified in pagination params.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/raw-checkpoint-list",
          label: "RawCheckpointList queries all checkpoints that match the given status.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/current-epoch",
          label: "CurrentEpoch queries the current epoch",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/delegation-lifecycle",
          label: "DelegationLifecycle queries the lifecycle of a given delegation",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/epochs-info",
          label: "EpochsInfo queries the metadata of epochs in a given range, depending on\nthe parameters in the pagination request. Th main use case will be querying\nthe latest epochs in time order.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/epoch-info",
          label: "EpochInfo queries the information of a given epoch",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/epoch-msgs",
          label: "EpochMsgs queries the messages of a given epoch",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/epoch-val-set",
          label: "EpochValSet queries the validator set of a given epoch",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/latest-epoch-msgs",
          label: "LatestEpochMsgs queries the messages within a given number of most recent\nepochs",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/epoching-params",
          label: "Params queries the parameters of the module.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/validator-lifecycle",
          label: "ValidatorLifecycle queries the lifecycle of a given validator",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/activated-height",
          label: "ActivatedHeight queries the height when BTC staking protocol is activated, i.e., the first height when\nthere exists 1 finality provider with voting power",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/list-blocks",
          label: "ListBlocks is a range query for blocks at a given status",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/block",
          label: "Block queries a block at a given height",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/list-evidences",
          label: "ListEvidences queries is a range query for evidences",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/evidence",
          label: "Evidence queries the first evidence which can be used for extracting the BTC SK",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/finality-provider-current-power",
          label: "FinalityProviderCurrentPower queries the voting power of a finality provider at the current height",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/finality-provider-power-at-height",
          label: "FinalityProviderPowerAtHeight queries the voting power of a finality provider at a given height",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/list-pub-rand-commit",
          label: "ListPubRandCommit is a range query for public randomness commitments of a given finality provider",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/list-public-randomness",
          label: "ListPublicRandomness is a range query for public randomness of a given finality provider\nNOTE: Babylon only has the knowledge of public randomness that is already revealed by\nfinality providers, i.e., the finality provider already provides a finality signature\nat the corresponding height",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/active-finality-providers-at-height",
          label: "ActiveFinalityProvidersAtHeight queries finality providers with non zero voting power at given height.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/finality-params",
          label: "Parameters queries the parameters of the module.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/signing-infos",
          label: "SigningInfos queries the signing info of all the active finality providers",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/signing-info",
          label: "SigningInfo queries the signing info of given finality provider BTC public key",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/votes-at-height",
          label: "VotesAtHeight queries finality providers who have signed the block at given height.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/reward-gauges",
          label: "RewardGauge queries the reward gauge of a given stakeholder address",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/btc-staking-gauge",
          label: "BTCStakingGauge queries the BTC staking gauge of a given height",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/delegator-withdraw-address",
          label: "DelegatorWithdrawAddress queries withdraw address of a delegator.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/delegation-rewards",
          label: "DelegationRewards queries the delegation rewards of given finality provider\nand delegator addresses",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/incentive-params",
          label: "Parameters queries the parameters of the module.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/reported-checkpoint-btc-height",
          label: "ReportedCheckpointBtcHeight returns the BTC light client height at which\nthe checkpoint with the given hash is reported back to Babylon",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/ended-epoch-btc-height",
          label: "EndedEpochBtcHeight returns the BTC light client height at provided epoch\nfinish",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/header",
          label: "Header queries the CZ header and fork headers at a given height.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/chain-list",
          label: "ChainList queries the list of chains that checkpoint to Babylon",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/chains-info",
          label: "ChainsInfo queries the latest info for a given list of chains in Babylon's view",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/epoch-chains-info",
          label: "EpochChainsInfo queries the latest info for a list of chains\nin a given epoch in Babylon's view",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/finalized-chain-info-until-height",
          label: "FinalizedChainInfoUntilHeight queries the BTC-finalised info no later than\nthe provided CZ height, with proofs",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/finalized-chains-info",
          label: "FinalizedChainsInfo queries the BTC-finalised info of chains with given IDs, with proofs",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/list-headers",
          label: "ListHeaders queries the headers of a chain in Babylon's view, with\npagination support",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/list-epoch-headers",
          label: "ListEpochHeaders queries the headers of a chain timestamped in a given\nepoch of Babylon, with pagination support",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/zone-concierge-params",
          label: "Params queries the parameters of the module.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/annual-provisions",
          label: "AnnualProvisions returns the current annual provisions.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/genesis-time",
          label: "GenesisTime returns the genesis time.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/inflation-rate",
          label: "InflationRate returns the current inflation rate.",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "CometBFT",
      items: [
        {
          type: "doc",
          id: "api/babylon-gRPC/broadcast-tx-sync",
          label: "Returns with the response from CheckTx. Does not wait for DeliverTx result.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/broadcast-tx-async",
          label: "Returns right away, with no response. Does not wait for CheckTx nor DeliverTx results.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/broadcast-tx-commit",
          label: "Returns with the responses from CheckTx and DeliverTx.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/check-tx",
          label: "Checks the transaction without executing it.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/health",
          label: "Node heartbeat",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/status",
          label: "Node Status",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/net-info",
          label: "Network information",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/dial-seeds",
          label: "Dial Seeds (Unsafe)",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/dial-peers",
          label: "Add Peers/Persistent Peers (unsafe)",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/blockchain",
          label: "Get block headers (max: 20) for minHeight <= height <= maxHeight.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/header",
          label: "Get header at a specified height",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/header-by-hash",
          label: "Get header by hash",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/block",
          label: "Get block at a specified height",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/block-by-hash",
          label: "Get block by hash",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/block-results",
          label: "Get block results at a specified height",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/commit",
          label: "Get commit results at a specified height",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/validators",
          label: "Get validator set at a specified height",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/genesis",
          label: "Get Genesis",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/genesis-chunked",
          label: "Get Genesis in multiple chunks",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/dump-consensus-state",
          label: "Get consensus state",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/consensus-state",
          label: "Get consensus state",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/consensus-params",
          label: "Get consensus parameters",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/unconfirmed-txs",
          label: "Get the list of unconfirmed transactions",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/num-unconfirmed-txs",
          label: "Get data about unconfirmed transactions",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/tx-search",
          label: "Search for transactions",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/block-search",
          label: "Search for blocks by FinalizeBlock events",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/tx",
          label: "Get transactions by hash",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/abci-info",
          label: "Get info about the application.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/abci-query",
          label: "Query the application for some information.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/babylon-gRPC/broadcast-evidence",
          label: "Broadcast evidence of the misbehavior.",
          className: "api-method get",
        },
      ],
    },
  ],
};

export default sidebar.apisidebar;
