import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebar: SidebarsConfig = {
  apisidebar: [
    {
      type: "doc",
      id: "api/staking-api/devnet/babylon-staking-api",
    },
    {
      type: "category",
      label: "shared",
      link: {
        type: "doc",
        id: "api/staking-api/devnet/shared",
      },
      items: [
        {
          type: "doc",
          id: "api/staking-api/devnet/get-health-check",
          label: "Health check endpoint",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/staking-api/devnet/check-delegation-v-1",
          label: "checkDelegationV1",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/staking-api/devnet/lookup-staker-public-keys",
          label: "Get stakers' public keys",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "v2",
      link: {
        type: "doc",
        id: "api/staking-api/devnet/v-2",
      },
      items: [
        {
          type: "doc",
          id: "api/staking-api/devnet/check-address-risk",
          label: "Checks address risk",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/staking-api/devnet/get-delegation-v-2",
          label: "Get a delegation",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/staking-api/devnet/get-delegations-v-2",
          label: "Get Delegations",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/staking-api/devnet/get-finality-providers-v-2",
          label: "List Finality Providers",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/staking-api/devnet/get-network-info",
          label: "getNetworkInfo",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/staking-api/devnet/get-prices",
          label: "getPrices",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/staking-api/devnet/get-staker-stats-v-2",
          label: "Get Staker Stats",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/staking-api/devnet/get-stats-v-2",
          label: "getStatsV2",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "v1",
      link: {
        type: "doc",
        id: "api/staking-api/devnet/v-1",
      },
      items: [
        {
          type: "doc",
          id: "api/staking-api/devnet/get-delegation-v-1",
          label: "getDelegationV1",
          className: "menu__list-item--deprecated api-method get",
        },
        {
          type: "doc",
          id: "api/staking-api/devnet/get-finality-providers-v-1",
          label: "Get Active Finality Providers (Deprecated)",
          className: "menu__list-item--deprecated api-method get",
        },
        {
          type: "doc",
          id: "api/staking-api/devnet/get-global-params-v-1",
          label: "getGlobalParamsV1",
          className: "menu__list-item--deprecated api-method get",
        },
        {
          type: "doc",
          id: "api/staking-api/devnet/get-staker-delegations-v-1",
          label: "getStakerDelegationsV1",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/staking-api/devnet/get-stats-v-1",
          label: "Get Overall Stats (Deprecated)",
          className: "menu__list-item--deprecated api-method get",
        },
        {
          type: "doc",
          id: "api/staking-api/devnet/get-staker-stats-v-1",
          label: "Get Staker Stats (Deprecated)",
          className: "menu__list-item--deprecated api-method get",
        },
        {
          type: "doc",
          id: "api/staking-api/devnet/unbond-delegation-v-1",
          label: "Unbond phase-1 delegation",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/staking-api/devnet/check-unbonding-eligibility-v-1",
          label: "Check unbonding eligibility",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Schemas",
      items: [
        {
          type: "doc",
          id: "api/staking-api/devnet/schemas/github-com-babylonlabs-io-staking-api-service-internal-shared-types-error",
          label: "github_com_babylonlabs-io_staking-api-service_internal_shared_types.Error",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/staking-api/devnet/schemas/handler-publicresponse-array-v-1-service-delegationpublic",
          label: "handler.PublicResponse-array_v1service_DelegationPublic",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/staking-api/devnet/schemas/handler-publicresponse-array-v-1-service-fpdetailspublic",
          label: "handler.PublicResponse-array_v1service_FpDetailsPublic",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/staking-api/devnet/schemas/handler-publicresponse-array-v-1-service-stakerstatspublic",
          label: "handler.PublicResponse-array_v1service_StakerStatsPublic",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/staking-api/devnet/schemas/handler-publicresponse-array-v-2-service-delegationpublic",
          label: "handler.PublicResponse-array_v2service_DelegationPublic",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/staking-api/devnet/schemas/handler-publicresponse-array-v-2-service-finalityproviderstatspublic",
          label: "handler.PublicResponse-array_v2service_FinalityProviderStatsPublic",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/staking-api/devnet/schemas/handler-publicresponse-map-string-float-64",
          label: "handler.PublicResponse-map_string_float64",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/staking-api/devnet/schemas/handler-publicresponse-map-string-string",
          label: "handler.PublicResponse-map_string_string",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/staking-api/devnet/schemas/handler-publicresponse-v-1-service-delegationpublic",
          label: "handler.PublicResponse-v1service_DelegationPublic",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/staking-api/devnet/schemas/handler-publicresponse-v-1-service-globalparamspublic",
          label: "handler.PublicResponse-v1service_GlobalParamsPublic",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/staking-api/devnet/schemas/handler-publicresponse-v-1-service-overallstatspublic",
          label: "handler.PublicResponse-v1service_OverallStatsPublic",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/staking-api/devnet/schemas/handler-publicresponse-v-2-handlers-addressscreeningresponse",
          label: "handler.PublicResponse-v2handlers_AddressScreeningResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/staking-api/devnet/schemas/handler-publicresponse-v-2-service-delegationpublic",
          label: "handler.PublicResponse-v2service_DelegationPublic",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/staking-api/devnet/schemas/handler-publicresponse-v-2-service-overallstatspublic",
          label: "handler.PublicResponse-v2service_OverallStatsPublic",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/staking-api/devnet/schemas/handler-publicresponse-v-2-service-stakerstatspublic",
          label: "handler.PublicResponse-v2service_StakerStatsPublic",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/staking-api/devnet/schemas/handler-paginationresponse",
          label: "handler.paginationResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/staking-api/devnet/schemas/indexertypes-bbnstakingparams",
          label: "indexertypes.BbnStakingParams",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/staking-api/devnet/schemas/indexertypes-btccheckpointparams",
          label: "indexertypes.BtcCheckpointParams",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/staking-api/devnet/schemas/map-string-float-64",
          label: "map_string_float64",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/staking-api/devnet/schemas/map-string-string",
          label: "map_string_string",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/staking-api/devnet/schemas/types-errorcode",
          label: "types.ErrorCode",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/staking-api/devnet/schemas/types-finalityproviderdescription",
          label: "types.FinalityProviderDescription",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/staking-api/devnet/schemas/types-finalityproviderqueryingstate",
          label: "types.FinalityProviderQueryingState",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/staking-api/devnet/schemas/v-1-handlers-delegationcheckpublicresponse",
          label: "v1handlers.DelegationCheckPublicResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/staking-api/devnet/schemas/v-1-handlers-unbonddelegationrequestpayload",
          label: "v1handlers.UnbondDelegationRequestPayload",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/staking-api/devnet/schemas/v-1-service-delegationpublic",
          label: "v1service.DelegationPublic",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/staking-api/devnet/schemas/v-1-service-fpdescriptionpublic",
          label: "v1service.FpDescriptionPublic",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/staking-api/devnet/schemas/v-1-service-fpdetailspublic",
          label: "v1service.FpDetailsPublic",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/staking-api/devnet/schemas/v-1-service-globalparamspublic",
          label: "v1service.GlobalParamsPublic",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/staking-api/devnet/schemas/v-1-service-overallstatspublic",
          label: "v1service.OverallStatsPublic",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/staking-api/devnet/schemas/v-1-service-stakerstatspublic",
          label: "v1service.StakerStatsPublic",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/staking-api/devnet/schemas/v-1-service-transactionpublic",
          label: "v1service.TransactionPublic",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/staking-api/devnet/schemas/v-1-service-versionedglobalparamspublic",
          label: "v1service.VersionedGlobalParamsPublic",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/staking-api/devnet/schemas/v-2-handlers-addressscreeningresponse",
          label: "v2handlers.AddressScreeningResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/staking-api/devnet/schemas/v-2-service-covenantsignature",
          label: "v2service.CovenantSignature",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/staking-api/devnet/schemas/v-2-service-delegationpublic",
          label: "v2service.DelegationPublic",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/staking-api/devnet/schemas/v-2-service-delegationstaking",
          label: "v2service.DelegationStaking",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/staking-api/devnet/schemas/v-2-service-delegationunbonding",
          label: "v2service.DelegationUnbonding",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/staking-api/devnet/schemas/v-2-service-finalityproviderstatspublic",
          label: "v2service.FinalityProviderStatsPublic",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/staking-api/devnet/schemas/v-2-service-networkinfopublic",
          label: "v2service.NetworkInfoPublic",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/staking-api/devnet/schemas/v-2-service-overallstatspublic",
          label: "v2service.OverallStatsPublic",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/staking-api/devnet/schemas/v-2-service-paramspublic",
          label: "v2service.ParamsPublic",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/staking-api/devnet/schemas/v-2-service-stakerstatspublic",
          label: "v2service.StakerStatsPublic",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/staking-api/devnet/schemas/v-2-service-stakingslashing",
          label: "v2service.StakingSlashing",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/staking-api/devnet/schemas/v-2-service-stakingstatuspublic",
          label: "v2service.StakingStatusPublic",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/staking-api/devnet/schemas/v-2-service-unbondingslashing",
          label: "v2service.UnbondingSlashing",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/staking-api/devnet/schemas/v-2-types-delegationstate",
          label: "v2types.DelegationState",
          className: "schema",
        },
      ],
    },
  ],
};

export default sidebar.apisidebar;
