import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebar: SidebarsConfig = {
  apisidebar: [
    {
      type: "doc",
      id: "api/staking-api/babylon-staking-api",
    },
    {
      type: "category",
      label: "shared",
      link: {
        type: "doc",
        id: "api/staking-api/shared",
      },
      items: [
        {
          type: "doc",
          id: "api/staking-api/health-check-endpoint",
          label: "Health check endpoint",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/staking-api/check-delegation-v-1",
          label: "Check delegation status",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/staking-api/get-stakers-public-keys",
          label: "Get stakers' public keys",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "v2",
      link: {
        type: "doc",
        id: "api/staking-api/v-2",
      },
      items: [
        {
          type: "doc",
          id: "api/staking-api/get-personalized-staking-apr",
          label: "Get personalized staking APR",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/staking-api/get-a-delegation",
          label: "Get a delegation",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/staking-api/get-delegations",
          label: "Get Delegations",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/staking-api/list-finality-providers",
          label: "List Finality Providers",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/staking-api/get-network-info",
          label: "Get network info",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/staking-api/get-prices",
          label: "Get prices",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/staking-api/get-staker-stats-v-2",
          label: "Get staker stats",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/staking-api/get-stats-v-2",
          label: "Get overall stats",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "v1",
      link: {
        type: "doc",
        id: "api/staking-api/v-1",
      },
      items: [
        {
          type: "doc",
          id: "api/staking-api/get-delegation-v-1",
          label: "Get delegation (Deprecated)",
          className: "menu__list-item--deprecated api-method get",
        },
        {
          type: "doc",
          id: "api/staking-api/get-active-finality-providers-deprecated",
          label: "Get Active Finality Providers (Deprecated)",
          className: "menu__list-item--deprecated api-method get",
        },
        {
          type: "doc",
          id: "api/staking-api/get-global-params-v-1",
          label: "Get global params (Deprecated)",
          className: "menu__list-item--deprecated api-method get",
        },
        {
          type: "doc",
          id: "api/staking-api/get-staker-delegations-v-1",
          label: "Get staker delegations",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/staking-api/get-overall-stats-deprecated",
          label: "Get Overall Stats (Deprecated)",
          className: "menu__list-item--deprecated api-method get",
        },
        {
          type: "doc",
          id: "api/staking-api/get-staker-stats-deprecated",
          label: "Get Staker Stats (Deprecated)",
          className: "menu__list-item--deprecated api-method get",
        },
        {
          type: "doc",
          id: "api/staking-api/unbond-phase-1-delegation",
          label: "Unbond phase-1 delegation",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/staking-api/check-unbonding-eligibility",
          label: "Check unbonding eligibility",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Schemas",
      items: [
        {
          type: "doc",
          id: "api/staking-api/schemas/types-error",
          label: "types.Error",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/staking-api/schemas/v-1-service-delegationpublicarray",
          label: "v1service.DelegationPublicArray",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/staking-api/schemas/v-1-service-fpdetailspublicarray",
          label: "v1service.FpDetailsPublicArray",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/staking-api/schemas/v-1-service-stakerstatspublicarray",
          label: "v1service.StakerStatsPublicArray",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/staking-api/schemas/v-2-service-delegationpublicarray",
          label: "v2service.DelegationPublicArray",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/staking-api/schemas/v-2-service-finalityproviderpublicarray",
          label: "v2service.FinalityProviderPublicArray",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/staking-api/schemas/types-pricesresponse",
          label: "types.PricesResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/staking-api/schemas/types-publickeymapresponse",
          label: "types.PublicKeyMapResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/staking-api/schemas/v-1-service-delegationpublicobject",
          label: "v1service.DelegationPublicObject",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/staking-api/schemas/v-1-service-globalparamspublicobject",
          label: "v1service.GlobalParamsPublicObject",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/staking-api/schemas/v-1-service-overallstatspublicobject",
          label: "v1service.OverallStatsPublicObject",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/staking-api/schemas/v-2-service-delegationpublicobject",
          label: "v2service.DelegationPublicObject",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/staking-api/schemas/v-2-service-overallstatspublicobject",
          label: "v2service.OverallStatsPublicObject",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/staking-api/schemas/v-2-service-stakerstatspublicobject",
          label: "v2service.StakerStatsPublicObject",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/staking-api/schemas/v-2-service-stakingaprpublicobject",
          label: "v2service.StakingAPRPublicObject",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/staking-api/schemas/types-paginationresponse",
          label: "types.PaginationResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/staking-api/schemas/indexertypes-bbnstakingparams",
          label: "indexertypes.BbnStakingParams",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/staking-api/schemas/indexertypes-btccheckpointparams",
          label: "indexertypes.BtcCheckpointParams",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/staking-api/schemas/types-mapstringfloat-64",
          label: "types.MapStringFloat64",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/staking-api/schemas/types-mapstringstring",
          label: "types.MapStringString",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/staking-api/schemas/types-delegationstate",
          label: "types.DelegationState",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/staking-api/schemas/types-errorcode",
          label: "types.ErrorCode",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/staking-api/schemas/types-finalityproviderdescription",
          label: "types.FinalityProviderDescription",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/staking-api/schemas/types-finalityproviderqueryingstate",
          label: "types.FinalityProviderQueryingState",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/staking-api/schemas/v-1-handlers-delegationcheckpublicresponse",
          label: "v1handlers.DelegationCheckPublicResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/staking-api/schemas/v-1-handlers-unbonddelegationrequestpayload",
          label: "v1handlers.UnbondDelegationRequestPayload",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/staking-api/schemas/v-1-service-delegationpublic",
          label: "v1service.DelegationPublic",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/staking-api/schemas/v-1-service-fpdescriptionpublic",
          label: "v1service.FpDescriptionPublic",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/staking-api/schemas/v-1-service-fpdetailspublic",
          label: "v1service.FpDetailsPublic",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/staking-api/schemas/v-1-service-globalparamspublic",
          label: "v1service.GlobalParamsPublic",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/staking-api/schemas/v-1-service-overallstatspublic",
          label: "v1service.OverallStatsPublic",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/staking-api/schemas/v-1-service-stakerstatspublic",
          label: "v1service.StakerStatsPublic",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/staking-api/schemas/v-1-service-transactionpublic",
          label: "v1service.TransactionPublic",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/staking-api/schemas/v-1-service-versionedglobalparamspublic",
          label: "v1service.VersionedGlobalParamsPublic",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/staking-api/schemas/v-2-service-covenantsignature",
          label: "v2service.CovenantSignature",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/staking-api/schemas/v-2-service-delegationpublic",
          label: "v2service.DelegationPublic",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/staking-api/schemas/v-2-service-delegationstaking",
          label: "v2service.DelegationStaking",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/staking-api/schemas/v-2-service-delegationunbonding",
          label: "v2service.DelegationUnbonding",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/staking-api/schemas/v-2-service-finalityproviderpublic",
          label: "v2service.FinalityProviderPublic",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/staking-api/schemas/v-2-service-networkinfopublic",
          label: "v2service.NetworkInfoPublic",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/staking-api/schemas/v-2-service-networkupgradepublic",
          label: "v2service.NetworkUpgradePublic",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/staking-api/schemas/v-2-service-overallstatspublic",
          label: "v2service.OverallStatsPublic",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/staking-api/schemas/v-2-service-popupgradepublic",
          label: "v2service.POPUpgradePublic",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/staking-api/schemas/v-2-service-paramspublic",
          label: "v2service.ParamsPublic",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/staking-api/schemas/v-2-service-stakerstatspublic",
          label: "v2service.StakerStatsPublic",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/staking-api/schemas/v-2-service-stakingaprpublic",
          label: "v2service.StakingAPRPublic",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/staking-api/schemas/v-2-service-stakingslashing",
          label: "v2service.StakingSlashing",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/staking-api/schemas/v-2-service-unbondingslashing",
          label: "v2service.UnbondingSlashing",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/staking-api/schemas/v-2-service-withdrawalinfo",
          label: "v2service.WithdrawalInfo",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/staking-api/schemas/v-2-service-apr",
          label: "v2service.apr",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/staking-api/schemas/v-2-types-delegationstate",
          label: "v2types.DelegationState",
          className: "schema",
        },
      ],
    },
  ],
};

export default sidebar.apisidebar;
