import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebar: SidebarsConfig = {
  apisidebar: [
    {
      type: "doc",
      id: "api/comet-bft/babylon-grpc-api-docs",
    },
    {
      type: "category",
      label: "btccheckpoint",
      link: {
        type: "doc",
        id: "api/comet-bft/btccheckpoint",
      },
      items: [
        {
          type: "doc",
          id: "api/comet-bft/btc-checkpoints-info",
          label: "BtcCheckpointsInfo",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/comet-bft/btc-checkpoint-params",
          label: "BtcCheckpointParams",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/comet-bft/btc-checkpoint-info",
          label: "BtcCheckpointInfo",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/comet-bft/epoch-submissions",
          label: "EpochSubmissions",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "btclightclient",
      link: {
        type: "doc",
        id: "api/comet-bft/btclightclient",
      },
      items: [
        {
          type: "doc",
          id: "api/comet-bft/base-header",
          label: "BaseHeader",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/comet-bft/contains",
          label: "Contains",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/comet-bft/contains-bytes",
          label: "ContainsBytes",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/comet-bft/header-depth",
          label: "HeaderDepth",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/comet-bft/hashes",
          label: "Hashes",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/comet-bft/main-chain",
          label: "MainChain",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/comet-bft/btc-light-client-params",
          label: "BtcLightClientParams",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/comet-bft/tip",
          label: "Tip",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "btcstaking",
      link: {
        type: "doc",
        id: "api/comet-bft/btcstaking",
      },
      items: [
        {
          type: "doc",
          id: "api/comet-bft/btc-delegation",
          label: "BTCDelegation",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/comet-bft/btc-delegations",
          label: "BTCDelegations",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/comet-bft/finality-providers",
          label: "FinalityProviders",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/comet-bft/finality-provider-delegations",
          label: "FinalityProviderDelegations",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/comet-bft/finality-provider",
          label: "FinalityProvider",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/comet-bft/largest-btc-re-org",
          label: "LargestBtcReOrg",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/comet-bft/params",
          label: "Params",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/comet-bft/params-by-btc-height",
          label: "ParamsByBTCHeight",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/comet-bft/params-by-version",
          label: "ParamsByVersion",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/comet-bft/params-versions",
          label: "ParamsVersions",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "btcstkconsumer",
      link: {
        type: "doc",
        id: "api/comet-bft/btcstkconsumer",
      },
      items: [
        {
          type: "doc",
          id: "api/comet-bft/consumer-registry-list",
          label: "ConsumerRegistryList",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/comet-bft/consumers-registry",
          label: "ConsumersRegistry",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/comet-bft/finality-provider-consumer",
          label: "FinalityProviderConsumer",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/comet-bft/finality-provider-consumer",
          label: "FinalityProviderConsumer",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/comet-bft/finality-providers-consumer",
          label: "FinalityProvidersConsumer",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/comet-bft/btc-stk-consumer-params",
          label: "BtcStkConsumerParams",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "checkpointing",
      link: {
        type: "doc",
        id: "api/comet-bft/checkpointing",
      },
      items: [
        {
          type: "doc",
          id: "api/comet-bft/bls-public-key-list",
          label: "BlsPublicKeyList",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/comet-bft/epoch-status",
          label: "EpochStatus",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/comet-bft/recent-epoch-status-count",
          label: "RecentEpochStatusCount",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/comet-bft/last-checkpoint-with-status",
          label: "LastCheckpointWithStatus",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/comet-bft/raw-checkpoint",
          label: "RawCheckpoint",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/comet-bft/raw-checkpoints",
          label: "RawCheckpoints",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/comet-bft/raw-checkpoint-list",
          label: "RawCheckpointList",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "epoching",
      link: {
        type: "doc",
        id: "api/comet-bft/epoching",
      },
      items: [
        {
          type: "doc",
          id: "api/comet-bft/current-epoch",
          label: "CurrentEpoch",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/comet-bft/delegation-lifecycle",
          label: "DelegationLifecycle",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/comet-bft/epochs-info",
          label: "EpochsInfo",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/comet-bft/epoch-info",
          label: "EpochInfo",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/comet-bft/epoch-msgs",
          label: "EpochMsgs",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/comet-bft/epoch-val-set",
          label: "EpochValSet queries the validator set of a given epoch",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/comet-bft/latest-epoch-msgs",
          label: "LatestEpochMsgs",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/comet-bft/epoching-params",
          label: "EpochingParams",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/comet-bft/validator-lifecycle",
          label: "ValidatorLifecycle",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "incentive",
      link: {
        type: "doc",
        id: "api/comet-bft/incentive",
      },
      items: [
        {
          type: "doc",
          id: "api/comet-bft/reward-gauges",
          label: "RewardGauge",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/comet-bft/btc-staking-gauge",
          label: "BTCStakingGauge",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/comet-bft/delegator-withdraw-address",
          label: "DelegatorWithdrawAddress",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/comet-bft/delegation-rewards",
          label: "DelegationRewards",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/comet-bft/incentive-params",
          label: "IncentiveParams",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "mint",
      link: {
        type: "doc",
        id: "api/comet-bft/mint",
      },
      items: [
        {
          type: "doc",
          id: "api/comet-bft/annual-provisions",
          label: "AnnualProvisions",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/comet-bft/genesis-time",
          label: "GenesisTime",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/comet-bft/inflation-rate",
          label: "InflationRate",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "finality",
      items: [
        {
          type: "doc",
          id: "api/comet-bft/activated-height",
          label: "ActivatedHeight",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/comet-bft/list-blocks",
          label: "ListBlocks",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/comet-bft/block",
          label: "Block",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/comet-bft/list-evidences",
          label: "ListEvidences",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/comet-bft/evidence",
          label: "Evidence",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/comet-bft/finality-provider-current-power",
          label: "FinalityProviderCurrentPower",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/comet-bft/finality-provider-power-at-height",
          label: "FinalityProviderPowerAtHeight",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/comet-bft/list-pub-rand-commit",
          label: "ListPubRandCommit",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/comet-bft/list-public-randomness",
          label: "ListPublicRandomness",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/comet-bft/active-finality-providers-at-height",
          label: "ActiveFinalityProvidersAtHeight",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/comet-bft/finality-params",
          label: "FinalityParams",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/comet-bft/signing-infos",
          label: "SigningInfos",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/comet-bft/signing-info",
          label: "SigningInfo",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/comet-bft/votes-at-height",
          label: "VotesAtHeight",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "monitor",
      items: [
        {
          type: "doc",
          id: "api/comet-bft/reported-checkpoint-btc-height",
          label: "ReportedCheckpointBtcHeight",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/comet-bft/ended-epoch-btc-height",
          label: "EndedEpochBtcHeight",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "zoneconcierge",
      items: [
        {
          type: "doc",
          id: "api/comet-bft/header",
          label: "Header",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/comet-bft/chain-list",
          label: "ChainList",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/comet-bft/chains-info",
          label: "ChainsInfo",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/comet-bft/epoch-chains-info",
          label: "EpochChainsInfo",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/comet-bft/finalized-chain-info-until-height",
          label: "FinalizedChainInfoUntilHeight",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/comet-bft/finalized-chains-info",
          label: "FinalizedChainsInfo",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/comet-bft/list-headers",
          label: "ListHeaders",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/comet-bft/list-epoch-headers",
          label: "ListEpochHeaders",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/comet-bft/zone-concierge-params",
          label: "ZoneConciergeParams",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "CometBFT",
      items: [
        {
          type: "doc",
          id: "api/comet-bft/broadcast-tx-sync",
          label: "broadcast_tx_sync",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/comet-bft/broadcast-tx-async",
          label: "broadcast_tx_async",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/comet-bft/broadcast-tx-commit",
          label: "broadcast_tx_commit",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/comet-bft/check-tx",
          label: "check_tx",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/comet-bft/health",
          label: "health",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/comet-bft/status",
          label: "status",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/comet-bft/net-info",
          label: "net_info",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/comet-bft/dial-seeds",
          label: "dial_seeds (unsafe)",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/comet-bft/dial-peers",
          label: "dial_peers (unsafe)",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/comet-bft/blockchain",
          label: "blockchain",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/comet-bft/header",
          label: "header",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/comet-bft/header-by-hash",
          label: "header_by_hash",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/comet-bft/block",
          label: "block",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/comet-bft/block-by-hash",
          label: "block_by_hash",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/comet-bft/block-results",
          label: "block_results",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/comet-bft/commit",
          label: "commit",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/comet-bft/validators",
          label: "validators",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/comet-bft/genesis",
          label: "genesis",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/comet-bft/genesis-chunked",
          label: "genesis_chunked",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/comet-bft/dump-consensus-state",
          label: "dump_consensus_state",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/comet-bft/consensus-state",
          label: "consensus_state",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/comet-bft/consensus-params",
          label: "consensus_params",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/comet-bft/unconfirmed-txs",
          label: "unconfirmed_txs",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/comet-bft/num-unconfirmed-txs",
          label: "num_unconfirmed_txs",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/comet-bft/tx-search",
          label: "tx_search",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/comet-bft/block-search",
          label: "block_search",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/comet-bft/tx",
          label: "tx",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/comet-bft/abci-info",
          label: "abci_info",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/comet-bft/abci-query",
          label: "abci_query",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/comet-bft/broadcast-evidence",
          label: "broadcast_evidence",
          className: "api-method get",
        },
      ],
    },
  ],
};

export default sidebar.apisidebar;
