name: Algolia DocSearch Scraper

on:
  push:
    branches:
      - main
      - dev

jobs:
  run-crawler:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set environment variables
        run: |
          if [ "${GITHUB_REF}" == "refs/heads/main" ]; then
            echo "CONFIG_FILE=docsearch.config.json" >> $GITHUB_ENV
          elif [ "${GITHUB_REF}" == "refs/heads/dev" ]; then
            echo "CONFIG_FILE=docsearch.config.dev.json" >> $GITHUB_ENV
          else
            echo "Unknown branch: ${GITHUB_REF}"
            exit 1
          fi

      - name: Run DocSearch scraper using Docker
        env:
          ALGOLIA_APP_ID: ${{ secrets.ALGOLIA_APP_ID }}
          ALGOLIA_API_KEY: ${{ secrets.ALGOLIA_API_KEY }}
          CONFIG_FILE: ${{ env.CONFIG_FILE }}
        working-directory: ./
        run: |
          docker run --rm \
            -v $(pwd):/app \
            -e "CONFIG=/app/${CONFIG_FILE}" \
            -e "ALGOLIA_APP_ID=${ALGOLIA_APP_ID}" \
            -e "ALGOLIA_API_KEY=${ALGOLIA_API_KEY}" \
            algolia/docsearch-scraper
