name: Algolia DocSearch Scraper

on:
  push:
    branches:
      - main
      - dev

jobs:
  run-crawler:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run DocSearch scraper using Docker
        env:
          ALGOLIA_APP_ID: ${{ secrets.ALGOLIA_APP_ID }}
          ALGOLIA_API_KEY: ${{ secrets.ALGOLIA_API_KEY }}
        working-directory: ./doc-babylonlabs-io
        run: |
          docker run --rm \
            -v $(pwd):/app \
            -e "CONFIG=/app/docsearch.config.json" \
            -e "ALGOLIA_APP_ID=${ALGOLIA_APP_ID}" \
            -e "ALGOLIA_API_KEY=${ALGOLIA_API_KEY}" \
            algolia/docsearch-scraper
